import type { Metadata } from "next";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={nunitoSans.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
